### ISSUE TITLE
Syntax error in the new version of this flake

### ISSUE THREAD

**Issue by thiloho** [almahdi/nix-thorium#2]
Just to inform you, in the updated version of the `flake.nix` file, so in the current state, if you try to run the flake with the command `nix run github:almahdi/nix-thorium`, you will get a syntax error:
```
error: syntax error, unexpected invalid token

       at /nix/store/jnfakkh8i00bmkajyxb1p154mmanwc3y-source/flake.nix:2:1:

            1| {
            2|   description = "Thorium using Nix Flake";
             | ^
            3|   inputs = {
```

I had a quick look at this, and if you inspect the contents of `flake.nix` with a code editor such as Visual Studio Code, you will see that there are many invalid symbols causing this problem.

The older/original version of the flake works fine, so you can work around the problem by referencing an older commit with `nix run github:almahdi/nix-thorium/16cbc264b5e7baf09cb895e8c5a49f7d915399d8`.

**Comment by Icey-Glitch** [comment]
sorry for this I was not expecting my fork to be merged and never got to finishing it.

**Comment by almahdi** [comment]
I honestly didn't expect anyone to use my repo. It was a test repo, I will not be supporting this anymore. I wanted to try Thorium on nix and be able to run it on multiple machines, hence the repo. I apologize for breaking it for you. I reverted the flake file to the old contents.
